WTF_CSRF_ENABLE=True
SECRET_KEY="SO_HARD"
MONGOALCHEMY_DATABASE="mood"


MAIL_SERVER="smtp.free.fr"
MAIL_PORT=465
MAIL_USE_SSL=True
MAIL_USERNAME="saturne@free.fr"
MAIL_PASSWORD="iit2kb0p"

SECURITY_EMAIL_SENDER="saturne@free.fr"
SECURITY_PASSWORD_HASH="pbkdf2_sha512"
SECURITY_PASSWORD_SALT="fhezikhfezk334lfhoe434534RFsfsRERfe"
SECURITY_CONFIRMABLE=False
SECURITY_REGISTERABLE=True
SECURITY_RECOVERABLE=True
SECURITY_CHANGEABLE=True
